### PR TITLE
feat: wip state store with sql server

### PR DESCRIPTION
**Pull request by mintxelas**
Hi!
This PR is just for showing what I've been doing on persistence and open a discussion. It sure is not production ready, it's not even finished :)
I must admit this is very humbling, I'm having a very hard time understanding the intention of the components. 
Thanks for any comments.

### CODE REVIEW

**Comment by tjaskula** [comment]
Hi @mintxelas . Thank you for the PR! I'll be going through to help you out the best I can :)

Just to understand, you'll be pushing more changes as you go to this PR, right ?

**Comment by mintxelas** [comment]
I'm not sure when I'll be able to spend some more time on it, but yes, I'll keep it updated. Right now this is basically exploration.

**Comment by tjaskula** [comment]
No problem, it's just to know so can I leave it open.

**Comment by mintxelas** [comment]
Won't be working on this for now, sorry.

**Pull request closed without merging**
